language: node_js
node_js: node

sudo: false  # use the new container-based Travis infrastructure
dist: trusty

cache:
  yarn: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - libunwind8-dev

before_install:
  - nvm install node
  - nvm use node
  - node --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - ./build.sh

after_script: greenkeeper-lockfile-upload

after_success: yarn run codecov