init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

install:
  - ps: Install-Product node ''

os: Visual Studio 2017
build_script:
  - cmd: bash build.sh
test: off
version: "Build #{build}"